Updated travis build to use netcoreapp1.0

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,11 +1,32 @@
 language: csharp
-mono:
- - beta
 
-install: curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | sh && source ~/.dnx/dnvm/dnvm.sh && dnvm upgrade
+before_install:
+  - export DOTNET_SDK_URL="https://go.microsoft.com/fwlink/?LinkID=809129"
+  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
 
-script:
-  cd codevalr-api/src/codevalr && dnu restore && dnu build && cd ../codevalr-api && dnu restore && dnu build
+    # Install .NET CLI
+  - mkdir $DOTNET_INSTALL_DIR
+  - curl -L $DOTNET_SDK_URL -o dotnet_package
+  - tar -xvzf dotnet_package -C $DOTNET_INSTALL_DIR
+
+    # Add dotnet to PATH
+  - export PATH="$DOTNET_INSTALL_DIR:$PATH"
+
+
+install:
+  # Display dotnet version info
+  - which dotnet;
+    if [ $? -eq 0 ]; then
+      echo "Using dotnet:";
+      dotnet --info;
+    else
+      echo "dotnet.exe not found"
+      exit 1;
+    fi
+
+  # Restore dependencies
+  - dotnet restore
+  - dotnet build -f netcoreapp1.0 ./codevalr-api/src/codevalr
 
 # whitelist
 branches:
